### ISSUE TITLE
Image won't start due to snakeoil key.

### ISSUE THREAD

**Issue by base698** [helmi03/docker-postgis#4]
Probably permissions related on the file, but would be nice if it just worked with docker run.

**Comment by md5** [comment]
I'm affected by this issue as well. Is there a straightforward workaround?

**Comment by md5** [comment]
When I move and recreate the /etc/ssl/private directory during the image build, the permission error goes away:

``` Dockerfile
from helmi03/docker-postgis:latest

run mv /etc/ssl/private /etc/ssl/private~ &&\
    cp -pr /etc/ssl/private~ /etc/ssl/private &&\
    rm -rf /etc/ssl/private~
```

I'm using AUFS as a driver and I'm wondering whether the problem here could be related to something mentioned in this comment about layering of directory permissions: https://github.com/dotcloud/docker/issues/783#issuecomment-19237045

**Comment by md5** [comment]
I just thought I'd mention that rebuilding this image from scratch using a recent Docker version (1.2.0) has solved this issue for me. Perhaps it would be good to kick off a new build on Docker Hub to hopefully get a more widely working image published.
